version: 2
jobs:

  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Run Build
          command: go build

  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Run Tests
          command: go test ./...
