apiVersion: v1
kind: Service
metadata:
  name: jpalp-backend-service
  labels:
    app: jpalp-backend
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: jpalp-backend
  type: LoadBalancer
