apiVersion: v1
kind: Pod
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo:latest
    ports:
    - containerPort: 27017
    volumeMounts:
    - mountPath: /var/lib/mongo
      name: mongo-volume
    # env:
    # - name: MYSQL_ROOT_PASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: db-secret
    #       key: mysql-password
    # - name: MYSQL_DATABASE
    #   valueFrom:
    #     secretKeyRef:
    #       name: db-secret
    #       key: database
  volumes:
  - name: mongo-volume


