apiVersion: v1
kind: Service
metadata:
  name: circleci-cd-demo-service
  labels:
    app: circleci-cd
spec:
  ports:
    - port: 8080
  selector:
    app: ci-deploy
    tier: backend
  type: LoadBalancer